spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
      platform: mssql
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.jdbc.core: INFO
